IF OBJECT_ID('dbo.Users', 'U') IS NOT NULL
BEGIN
    DROP TABLE dbo.Users;
    PRINT 'Tabulka Users byla smazána.';
END
GO
BEGIN
	CREATE TABLE Users (
		Id INT PRIMARY KEY IDENTITY(1,1),
		RoleId INT NOT NULL,
		GroupId INT NOT NULL,
		UserLogin NVARCHAR(100) UNIQUE NOT NULL,
		UserName NVARCHAR(100) NOT NULL,
		UserSurname NVARCHAR(255) NOT NULL,
		UserPassword NVARCHAR(200) NOT NULL,
		UserDescription NVARCHAR(MAX) NOT NULL DEFAULT '',
		SystemImagesId INT NOT NULL,
		BackupKey NVARCHAR(200) NOT NULL DEFAULT '',
		Active BIT NOT NULL DEFAULT 1,
		Activated BIT NOT NULL DEFAULT 0,
		CreateDateTime DATETIME2(7) NOT NULL DEFAULT SYSUTCDATETIME(),
		CreateAuthor INT NOT NULL DEFAULT 0
	);
END
GO